### PR TITLE
Define physical buttons locations

### PR DESCRIPTION
**Pull request by AkiraNoSushi**

### CODE REVIEW

**Comment by Deepak5310** [comment]
Remove non-existing physical volume up/down dimens.

**Comment by AkiraNoSushi** [comment]
> Remove non-existing physical volume up/down dimens.

Well, I could but Pixel devices add those dimens as well 👀 maybe it's used elsewhere?

**Comment by Deepak5310** [comment]
Pixel devices does not add those dimens anymore. It was completely removed when Android 12L was released. you can check sources

**Comment by AkiraNoSushi** [comment]
> Pixel devices does not add those dimens anymore. It was completely removed when Android 12L was released. you can check sources

https://android.googlesource.com/device/google/redfin/+/refs/tags/android-13.0.0_r3/redfin/overlay/frameworks/base/packages/SystemUI/res/values/dimens.xml 👀

**Pull request closed without merging**
